import { CountryType } from "./const-type";

export const Countries: CountryType[] = [
  {
    code: "AF",
    name: "Afghanistan",
    locale: "افغانستان",
    googleNames: ["Afghanistan", "Islamic Republic of Afghanistan"],
    currencyCode: "AFN",
    currency: "؋",
    telCode: 93,
    flag: "🇦🇫",
  },
  {
    code: "AL",
    name: "Albania",
    locale: "Shqipëri",
    googleNames: ["Albania", "Republic of Albania"],
    currencyCode: "ALL",
    currency: "L",
    telCode: 355,
    flag: "🇦🇱",
  },
  {
    code: "DZ",
    name: "Algeria",
    locale: "الجزائر",
    googleNames: ["Algeria", "People's Democratic Republic of Algeria"],
    currencyCode: "DZD",
    currency: "د.ج",
    telCode: 213,
    flag: "🇩🇿",
  },
  {
    code: "AD",
    name: "Andorra",
    locale: "Andorra",
    googleNames: ["Andorra", "Principality of Andorra"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 376,
    flag: "🇦🇩",
  },
  {
    code: "AO",
    name: "Angola",
    locale: "Angola",
    googleNames: ["Angola", "Republic of Angola"],
    currencyCode: "AOA",
    currency: "Kz",
    telCode: 244,
    flag: "🇦🇴",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    locale: "Antigua and Barbuda",
    googleNames: ["Antigua and Barbuda"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1268,
    flag: "🇦🇬",
  },
  {
    code: "AR",
    name: "Argentina",
    locale: "Argentina",
    googleNames: ["Argentina", "Argentine Republic"],
    currencyCode: "ARS",
    currency: "$",
    telCode: 54,
    flag: "🇦🇷",
  },
  {
    code: "AM",
    name: "Armenia",
    locale: "Հայաստան",
    googleNames: ["Armenia", "Republic of Armenia"],
    currencyCode: "AMD",
    currency: "֏",
    telCode: 374,
    flag: "🇦🇲",
  },
  {
    code: "AU",
    name: "Australia",
    locale: "Australia",
    googleNames: ["Australia", "Commonwealth of Australia"],
    currencyCode: "AUD",
    currency: "$",
    telCode: 61,
    flag: "🇦🇺",
  },
  {
    code: "AT",
    name: "Austria",
    locale: "Österreich",
    googleNames: ["Austria", "Republic of Austria"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 43,
    flag: "🇦🇹",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    locale: "Azərbaycan",
    googleNames: ["Azerbaijan", "Republic of Azerbaijan"],
    currencyCode: "AZN",
    currency: "₼",
    telCode: 994,
    flag: "🇦🇿",
  },
  {
    code: "BS",
    name: "Bahamas",
    locale: "Bahamas",
    googleNames: ["Bahamas", "Commonwealth of the Bahamas"],
    currencyCode: "BSD",
    currency: "$",
    telCode: 1242,
    flag: "🇧🇸",
  },
  {
    code: "BH",
    name: "Bahrain",
    locale: "البحرين",
    googleNames: ["Bahrain", "Kingdom of Bahrain"],
    currencyCode: "BHD",
    currency: ".د.ب",
    telCode: 973,
    flag: "🇧🇭",
  },
  {
    code: "BD",
    name: "Bangladesh",
    locale: "বাংলাদেশ",
    googleNames: ["Bangladesh", "People's Republic of Bangladesh"],
    currencyCode: "BDT",
    currency: "৳",
    telCode: 880,
    flag: "🇧🇩",
  },
  {
    code: "BB",
    name: "Barbados",
    locale: "Barbados",
    googleNames: ["Barbados"],
    currencyCode: "BBD",
    currency: "$",
    telCode: 1246,
    flag: "🇧🇧",
  },
  {
    code: "BY",
    name: "Belarus",
    locale: "Беларусь",
    googleNames: ["Belarus", "Republic of Belarus"],
    currencyCode: "BYN",
    currency: "Br",
    telCode: 375,
    flag: "🇧🇾",
  },
  {
    code: "BE",
    name: "Belgium",
    locale: "België",
    googleNames: ["Belgium", "Kingdom of Belgium"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 32,
    flag: "🇧🇪",
  },
  {
    code: "BZ",
    name: "Belize",
    locale: "Belize",
    googleNames: ["Belize"],
    currencyCode: "BZD",
    currency: "$",
    telCode: 501,
    flag: "🇧🇿",
  },
  {
    code: "BJ",
    name: "Benin",
    locale: "Bénin",
    googleNames: ["Benin", "Republic of Benin"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 229,
    flag: "🇧🇯",
  },
  {
    code: "BT",
    name: "Bhutan",
    locale: "འབྲུག",
    googleNames: ["Bhutan", "Kingdom of Bhutan"],
    currencyCode: "BTN",
    currency: "Nu.",
    telCode: 975,
    flag: "🇧🇹",
  },
  {
    code: "BO",
    name: "Bolivia",
    locale: "Bolivia",
    googleNames: ["Bolivia", "Plurinational State of Bolivia"],
    currencyCode: "BOB",
    currency: "Bs.",
    telCode: 591,
    flag: "🇧🇴",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    locale: "Bosna i Hercegovina",
    googleNames: ["Bosnia and Herzegovina"],
    currencyCode: "BAM",
    currency: "KM",
    telCode: 387,
    flag: "🇧🇦",
  },
  {
    code: "BW",
    name: "Botswana",
    locale: "Botswana",
    googleNames: ["Botswana", "Republic of Botswana"],
    currencyCode: "BWP",
    currency: "P",
    telCode: 267,
    flag: "🇧🇼",
  },
  {
    code: "BR",
    name: "Brazil",
    locale: "Brasil",
    googleNames: ["Brazil", "Federative Republic of Brazil"],
    currencyCode: "BRL",
    currency: "R$",
    telCode: 55,
    flag: "🇧🇷",
  },
  {
    code: "BN",
    name: "Brunei",
    locale: "Brunei",
    googleNames: ["Brunei", "Nation of Brunei"],
    currencyCode: "BND",
    currency: "$",
    telCode: 673,
    flag: "🇧🇳",
  },
  {
    code: "BG",
    name: "Bulgaria",
    locale: "България",
    googleNames: ["Bulgaria", "Republic of Bulgaria"],
    currencyCode: "BGN",
    currency: "лв",
    telCode: 359,
    flag: "🇧🇬",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    locale: "Burkina Faso",
    googleNames: ["Burkina Faso"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 226,
    flag: "🇧🇫",
  },
  {
    code: "BI",
    name: "Burundi",
    locale: "Uburundi",
    googleNames: ["Burundi", "Republic of Burundi"],
    currencyCode: "BIF",
    currency: "Fr",
    telCode: 257,
    flag: "🇧🇮",
  },
  {
    code: "CV",
    name: "Cabo Verde",
    locale: "Kabu Verdi",
    googleNames: ["Cabo Verde", "Cape Verde"],
    currencyCode: "CVE",
    currency: "$",
    telCode: 238,
    flag: "🇨🇻",
  },
  {
    code: "KH",
    name: "Cambodia",
    locale: "កម្ពុជា",
    googleNames: ["Cambodia", "Kingdom of Cambodia"],
    currencyCode: "KHR",
    currency: "៛",
    telCode: 855,
    flag: "🇰🇭",
  },
  {
    code: "CM",
    name: "Cameroon",
    locale: "Cameroun",
    googleNames: ["Cameroon", "Republic of Cameroon"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 237,
    flag: "🇨🇲",
  },
  {
    code: "CA",
    name: "Canada",
    locale: "Canada",
    googleNames: ["Canada"],
    currencyCode: "CAD",
    currency: "$",
    telCode: 1,
    flag: "🇨🇦",
  },
  {
    code: "CF",
    name: "Central African Republic",
    locale: "République centrafricaine",
    googleNames: ["Central African Republic"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 236,
    flag: "🇨🇫",
  },
  {
    code: "TD",
    name: "Chad",
    locale: "Tchad",
    googleNames: ["Chad", "Republic of Chad"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 235,
    flag: "🇹🇩",
  },
  {
    code: "CL",
    name: "Chile",
    locale: "Chile",
    googleNames: ["Chile", "Republic of Chile"],
    currencyCode: "CLP",
    currency: "$",
    telCode: 56,
    flag: "🇨🇱",
  },
  {
    code: "CN",
    name: "China",
    locale: "中国",
    googleNames: ["China", "People's Republic of China"],
    currencyCode: "CNY",
    currency: "¥",
    telCode: 86,
    flag: "🇨🇳",
  },
  {
    code: "CO",
    name: "Colombia",
    locale: "Colombia",
    googleNames: ["Colombia", "Republic of Colombia"],
    currencyCode: "COP",
    currency: "$",
    telCode: 57,
    flag: "🇨🇴",
  },
  {
    code: "KM",
    name: "Comoros",
    locale: "جزر القمر",
    googleNames: ["Comoros", "Union of the Comoros"],
    currencyCode: "KMF",
    currency: "Fr",
    telCode: 269,
    flag: "🇰🇲",
  },
  {
    code: "CG",
    name: "Congo",
    locale: "Congo",
    googleNames: ["Congo", "Republic of the Congo"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 242,
    flag: "🇨🇬",
  },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    locale: "Congo, République démocratique du",
    googleNames: ["Democratic Republic of the Congo", "DR Congo"],
    currencyCode: "CDF",
    currency: "Fr",
    telCode: 243,
    flag: "🇨🇩",
  },
  {
    code: "CR",
    name: "Costa Rica",
    locale: "Costa Rica",
    googleNames: ["Costa Rica", "Republic of Costa Rica"],
    currencyCode: "CRC",
    currency: "₡",
    telCode: 506,
    flag: "🇨🇷",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    locale: "Côte d'Ivoire",
    googleNames: ["Côte d'Ivoire", "Ivory Coast"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 225,
    flag: "🇨🇮",
  },
  {
    code: "HR",
    name: "Croatia",
    locale: "Hrvatska",
    googleNames: ["Croatia", "Republic of Croatia"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 385,
    flag: "🇭🇷",
  },
  {
    code: "CU",
    name: "Cuba",
    locale: "Cuba",
    googleNames: ["Cuba", "Republic of Cuba"],
    currencyCode: "CUP",
    currency: "$",
    telCode: 53,
    flag: "🇨🇺",
  },
  {
    code: "CY",
    name: "Cyprus",
    locale: "Κύπρος",
    googleNames: ["Cyprus", "Republic of Cyprus"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 357,
    flag: "🇨🇾",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    locale: "Česko",
    googleNames: ["Czech Republic", "Czechia"],
    currencyCode: "CZK",
    currency: "Kč",
    telCode: 420,
    flag: "🇨🇿",
  },
  {
    code: "DK",
    name: "Denmark",
    locale: "Danmark",
    googleNames: ["Denmark", "Kingdom of Denmark"],
    currencyCode: "DKK",
    currency: "kr",
    telCode: 45,
    flag: "🇩🇰",
  },
  {
    code: "DJ",
    name: "Djibouti",
    locale: "جيبوتي",
    googleNames: ["Djibouti", "Republic of Djibouti"],
    currencyCode: "DJF",
    currency: "Fr",
    telCode: 253,
    flag: "🇩🇯",
  },
  {
    code: "DM",
    name: "Dominica",
    locale: "Dominica",
    googleNames: ["Dominica", "Commonwealth of Dominica"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1767,
    flag: "🇩🇲",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    locale: "República Dominicana",
    googleNames: ["Dominican Republic"],
    currencyCode: "DOP",
    currency: "$",
    telCode: 1809,
    flag: "🇩🇴",
  },
  {
    code: "EC",
    name: "Ecuador",
    locale: "Ecuador",
    googleNames: ["Ecuador", "Republic of Ecuador"],
    currencyCode: "USD",
    currency: "$",
    telCode: 593,
    flag: "🇪🇨",
  },
  {
    code: "EG",
    name: "Egypt",
    locale: "مصر",
    googleNames: ["Egypt", "Arab Republic of Egypt"],
    currencyCode: "EGP",
    currency: "£",
    telCode: 20,
    flag: "🇪🇬",
  },
  {
    code: "SV",
    name: "El Salvador",
    locale: "El Salvador",
    googleNames: ["El Salvador", "Republic of El Salvador"],
    currencyCode: "USD",
    currency: "$",
    telCode: 503,
    flag: "🇸🇻",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    locale: "Guinea Ecuatorial",
    googleNames: ["Equatorial Guinea", "Republic of Equatorial Guinea"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 240,
    flag: "🇬🇶",
  },
  {
    code: "ER",
    name: "Eritrea",
    locale: "ኤርትራ",
    googleNames: ["Eritrea", "State of Eritrea"],
    currencyCode: "ERN",
    currency: "Nfk",
    telCode: 291,
    flag: "🇪🇷",
  },
  {
    code: "EE",
    name: "Estonia",
    locale: "Eesti",
    googleNames: ["Estonia", "Republic of Estonia"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 372,
    flag: "🇪🇪",
  },
  {
    code: "SZ",
    name: "Eswatini",
    locale: "Eswatini",
    googleNames: ["Eswatini", "Kingdom of Eswatini"],
    currencyCode: "SZL",
    currency: "L",
    telCode: 268,
    flag: "🇸🇿",
  },
  {
    code: "ET",
    name: "Ethiopia",
    locale: "ኢትዮጵያ",
    googleNames: ["Ethiopia", "Federal Democratic Republic of Ethiopia"],
    currencyCode: "ETB",
    currency: "Br",
    telCode: 251,
    flag: "🇪🇹",
  },
  {
    code: "FJ",
    name: "Fiji",
    locale: "Fiji",
    googleNames: ["Fiji", "Republic of Fiji"],
    currencyCode: "FJD",
    currency: "$",
    telCode: 679,
    flag: "🇫🇯",
  },
  {
    code: "FI",
    name: "Finland",
    locale: "Suomi",
    googleNames: ["Finland", "Republic of Finland"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 358,
    flag: "🇫🇮",
  },
  {
    code: "FR",
    name: "France",
    locale: "France",
    googleNames: ["France", "French Republic"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 33,
    flag: "🇫🇷",
  },
  {
    code: "GA",
    name: "Gabon",
    locale: "Gabon",
    googleNames: ["Gabon", "Gabonese Republic"],
    currencyCode: "XAF",
    currency: "CFA",
    telCode: 241,
    flag: "🇬🇦",
  },
  {
    code: "GM",
    name: "Gambia",
    locale: "Gambia",
    googleNames: ["Gambia", "Republic of the Gambia"],
    currencyCode: "GMD",
    currency: "D",
    telCode: 220,
    flag: "🇬🇲",
  },
  {
    code: "GE",
    name: "Georgia",
    locale: "საქართველო",
    googleNames: ["Georgia"],
    currencyCode: "GEL",
    currency: "₾",
    telCode: 995,
    flag: "🇬🇪",
  },
  {
    code: "DE",
    name: "Germany",
    locale: "Deutschland",
    googleNames: ["Germany", "Federal Republic of Germany"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 49,
    flag: "🇩🇪",
  },
  {
    code: "GH",
    name: "Ghana",
    locale: "Ghana",
    googleNames: ["Ghana", "Republic of Ghana"],
    currencyCode: "GHS",
    currency: "₵",
    telCode: 233,
    flag: "🇬🇭",
  },
  {
    code: "GR",
    name: "Greece",
    locale: "Ελλάδα",
    googleNames: ["Greece", "Hellenic Republic"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 30,
    flag: "🇬🇷",
  },
  {
    code: "GD",
    name: "Grenada",
    locale: "Grenada",
    googleNames: ["Grenada"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1473,
    flag: "🇬🇩",
  },
  {
    code: "GT",
    name: "Guatemala",
    locale: "Guatemala",
    googleNames: ["Guatemala", "Republic of Guatemala"],
    currencyCode: "GTQ",
    currency: "Q",
    telCode: 502,
    flag: "🇬🇹",
  },
  {
    code: "GN",
    name: "Guinea",
    locale: "Guinée",
    googleNames: ["Guinea", "Republic of Guinea"],
    currencyCode: "GNF",
    currency: "Fr",
    telCode: 224,
    flag: "🇬🇳",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    locale: "Guiné-Bissau",
    googleNames: ["Guinea-Bissau", "Republic of Guinea-Bissau"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 245,
    flag: "🇬🇼",
  },
  {
    code: "GY",
    name: "Guyana",
    locale: "Guyana",
    googleNames: ["Guyana", "Co-operative Republic of Guyana"],
    currencyCode: "GYD",
    currency: "$",
    telCode: 592,
    flag: "🇬🇾",
  },
  {
    code: "HT",
    name: "Haiti",
    locale: "Haïti",
    googleNames: ["Haiti", "Republic of Haiti"],
    currencyCode: "HTG",
    currency: "G",
    telCode: 509,
    flag: "🇭🇹",
  },
  {
    code: "HN",
    name: "Honduras",
    locale: "Honduras",
    googleNames: ["Honduras", "Republic of Honduras"],
    currencyCode: "HNL",
    currency: "L",
    telCode: 504,
    flag: "🇭🇳",
  },
  {
    code: "HU",
    name: "Hungary",
    locale: "Magyarország",
    googleNames: ["Hungary"],
    currencyCode: "HUF",
    currency: "Ft",
    telCode: 36,
    flag: "🇭🇺",
  },
  {
    code: "IS",
    name: "Iceland",
    locale: "Ísland",
    googleNames: ["Iceland", "Republic of Iceland"],
    currencyCode: "ISK",
    currency: "kr",
    telCode: 354,
    flag: "🇮🇸",
  },
  {
    code: "IN",
    name: "India",
    locale: "भारत",
    googleNames: ["India", "Republic of India", "Bharath"],
    currencyCode: "INR",
    currency: "₹",
    telCode: 91,
    flag: "🇮🇳",
  },
  {
    code: "ID",
    name: "Indonesia",
    locale: "Indonesia",
    googleNames: ["Indonesia", "Republic of Indonesia"],
    currencyCode: "IDR",
    currency: "Rp",
    telCode: 62,
    flag: "🇮🇩",
  },
  {
    code: "IR",
    name: "Iran",
    locale: "ایران",
    googleNames: ["Iran", "Islamic Republic of Iran"],
    currencyCode: "IRR",
    currency: "﷼",
    telCode: 98,
    flag: "🇮🇷",
  },
  {
    code: "IQ",
    name: "Iraq",
    locale: "العراق",
    googleNames: ["Iraq", "Republic of Iraq"],
    currencyCode: "IQD",
    currency: "ع.د",
    telCode: 964,
    flag: "🇮🇶",
  },
  {
    code: "IE",
    name: "Ireland",
    locale: "Éire",
    googleNames: ["Ireland"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 353,
    flag: "🇮🇪",
  },
  {
    code: "IL",
    name: "Israel",
    locale: "ישראל",
    googleNames: ["Israel", "State of Israel"],
    currencyCode: "ILS",
    currency: "₪",
    telCode: 972,
    flag: "🇮🇱",
  },
  {
    code: "IT",
    name: "Italy",
    locale: "Italia",
    googleNames: ["Italy", "Italian Republic"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 39,
    flag: "🇮🇹",
  },
  {
    code: "JM",
    name: "Jamaica",
    locale: "Jamaica",
    googleNames: ["Jamaica"],
    currencyCode: "JMD",
    currency: "$",
    telCode: 1876,
    flag: "🇯🇲",
  },
  {
    code: "JP",
    name: "Japan",
    locale: "日本",
    googleNames: ["Japan"],
    currencyCode: "JPY",
    currency: "¥",
    telCode: 81,
    flag: "🇯🇵",
  },
  {
    code: "JO",
    name: "Jordan",
    locale: "الأردن",
    googleNames: ["Jordan", "Hashemite Kingdom of Jordan"],
    currencyCode: "JOD",
    currency: "د.ا",
    telCode: 962,
    flag: "🇯🇴",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    locale: "Қазақстан",
    googleNames: ["Kazakhstan", "Republic of Kazakhstan"],
    currencyCode: "KZT",
    currency: "₸",
    telCode: 7,
    flag: "🇰🇿",
  },
  {
    code: "KE",
    name: "Kenya",
    locale: "Kenya",
    googleNames: ["Kenya", "Republic of Kenya"],
    currencyCode: "KES",
    currency: "Sh",
    telCode: 254,
    flag: "🇰🇪",
  },
  {
    code: "KI",
    name: "Kiribati",
    locale: "Kiribati",
    googleNames: ["Kiribati", "Republic of Kiribati"],
    currencyCode: "AUD",
    currency: "$",
    telCode: 686,
    flag: "🇰🇮",
  },
  {
    code: "KP",
    name: "North Korea",
    locale: "조선",
    googleNames: ["North Korea", "Democratic People's Republic of Korea"],
    currencyCode: "KPW",
    currency: "₩",
    telCode: 850,
    flag: "🇰🇵",
  },
  {
    code: "KR",
    name: "South Korea",
    locale: "대한민국",
    googleNames: ["South Korea", "Republic of Korea"],
    currencyCode: "KRW",
    currency: "₩",
    telCode: 82,
    flag: "🇰🇷",
  },
  {
    code: "KW",
    name: "Kuwait",
    locale: "الكويت",
    googleNames: ["Kuwait", "State of Kuwait"],
    currencyCode: "KWD",
    currency: "د.ك",
    telCode: 965,
    flag: "🇰🇼",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    locale: "Кыргызстан",
    googleNames: ["Kyrgyzstan", "Kyrgyz Republic"],
    currencyCode: "KGS",
    currency: "с",
    telCode: 996,
    flag: "🇰🇬",
  },
  {
    code: "LA",
    name: "Laos",
    locale: "ລາວ",
    googleNames: ["Laos", "Lao People's Democratic Republic"],
    currencyCode: "LAK",
    currency: "₭",
    telCode: 856,
    flag: "🇱🇦",
  },
  {
    code: "LV",
    name: "Latvia",
    locale: "Latvija",
    googleNames: ["Latvia", "Republic of Latvia"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 371,
    flag: "🇱🇻",
  },
  {
    code: "LB",
    name: "Lebanon",
    locale: "لبنان",
    googleNames: ["Lebanon", "Lebanese Republic"],
    currencyCode: "LBP",
    currency: "ل.ل",
    telCode: 961,
    flag: "🇱🇧",
  },
  {
    code: "LS",
    name: "Lesotho",
    locale: "Lesotho",
    googleNames: ["Lesotho", "Kingdom of Lesotho"],
    currencyCode: "LSL",
    currency: "L",
    telCode: 266,
    flag: "🇱🇸",
  },
  {
    code: "LR",
    name: "Liberia",
    locale: "Liberia",
    googleNames: ["Liberia", "Republic of Liberia"],
    currencyCode: "LRD",
    currency: "$",
    telCode: 231,
    flag: "🇱🇷",
  },
  {
    code: "LY",
    name: "Libya",
    locale: "ليبيا",
    googleNames: ["Libya"],
    currencyCode: "LYD",
    currency: "ل.د",
    telCode: 218,
    flag: "🇱🇾",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    locale: "Liechtenstein",
    googleNames: ["Liechtenstein", "Principality of Liechtenstein"],
    currencyCode: "CHF",
    currency: "Fr",
    telCode: 423,
    flag: "🇱🇮",
  },
  {
    code: "LT",
    name: "Lithuania",
    locale: "Lietuva",
    googleNames: ["Lithuania", "Republic of Lithuania"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 370,
    flag: "🇱🇹",
  },
  {
    code: "LU",
    name: "Luxembourg",
    locale: "Luxembourg",
    googleNames: ["Luxembourg", "Grand Duchy of Luxembourg"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 352,
    flag: "🇱🇺",
  },
  {
    code: "MG",
    name: "Madagascar",
    locale: "Madagasikara",
    googleNames: ["Madagascar", "Republic of Madagascar"],
    currencyCode: "MGA",
    currency: "Ar",
    telCode: 261,
    flag: "🇲🇬",
  },
  {
    code: "MW",
    name: "Malawi",
    locale: "Malawi",
    googleNames: ["Malawi", "Republic of Malawi"],
    currencyCode: "MWK",
    currency: "MK",
    telCode: 265,
    flag: "🇲🇼",
  },
  {
    code: "MY",
    name: "Malaysia",
    locale: "Malaysia",
    googleNames: ["Malaysia"],
    currencyCode: "MYR",
    currency: "RM",
    telCode: 60,
    flag: "🇲🇾",
  },
  {
    code: "MV",
    name: "Maldives",
    locale: "ދިވެހިރާއްޖެ",
    googleNames: ["Maldives", "Republic of Maldives"],
    currencyCode: "MVR",
    currency: "Rf",
    telCode: 960,
    flag: "🇲🇻",
  },
  {
    code: "ML",
    name: "Mali",
    locale: "Mali",
    googleNames: ["Mali", "Republic of Mali"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 223,
    flag: "🇲🇱",
  },
  {
    code: "MT",
    name: "Malta",
    locale: "Malta",
    googleNames: ["Malta", "Republic of Malta"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 356,
    flag: "🇲🇹",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    locale: "Marshall Islands",
    googleNames: ["Marshall Islands", "Republic of the Marshall Islands"],
    currencyCode: "USD",
    currency: "$",
    telCode: 692,
    flag: "🇲🇭",
  },
  {
    code: "MR",
    name: "Mauritania",
    locale: "موريتانيا",
    googleNames: ["Mauritania", "Islamic Republic of Mauritania"],
    currencyCode: "MRU",
    currency: "UM",
    telCode: 222,
    flag: "🇲🇷",
  },
  {
    code: "MU",
    name: "Mauritius",
    locale: "Maurice",
    googleNames: ["Mauritius", "Republic of Mauritius"],
    currencyCode: "MUR",
    currency: "₨",
    telCode: 230,
    flag: "🇲🇺",
  },
  {
    code: "MX",
    name: "Mexico",
    locale: "México",
    googleNames: ["Mexico", "United Mexican States"],
    currencyCode: "MXN",
    currency: "$",
    telCode: 52,
    flag: "🇲🇽",
  },
  {
    code: "FM",
    name: "Micronesia",
    locale: "Micronesia",
    googleNames: ["Micronesia", "Federated States of Micronesia"],
    currencyCode: "USD",
    currency: "$",
    telCode: 691,
    flag: "🇫🇲",
  },
  {
    code: "MD",
    name: "Moldova",
    locale: "Moldova",
    googleNames: ["Moldova", "Republic of Moldova"],
    currencyCode: "MDL",
    currency: "L",
    telCode: 373,
    flag: "🇲🇩",
  },
  {
    code: "MC",
    name: "Monaco",
    locale: "Monaco",
    googleNames: ["Monaco", "Principality of Monaco"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 377,
    flag: "🇲🇨",
  },
  {
    code: "MN",
    name: "Mongolia",
    locale: "Монгол",
    googleNames: ["Mongolia"],
    currencyCode: "MNT",
    currency: "₮",
    telCode: 976,
    flag: "🇲🇳",
  },
  {
    code: "ME",
    name: "Montenegro",
    locale: "Crna Gora",
    googleNames: ["Montenegro"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 382,
    flag: "🇲🇪",
  },
  {
    code: "MA",
    name: "Morocco",
    locale: "المغرب",
    googleNames: ["Morocco", "Kingdom of Morocco"],
    currencyCode: "MAD",
    currency: "د.م.",
    telCode: 212,
    flag: "🇲🇦",
  },
  {
    code: "MZ",
    name: "Mozambique",
    locale: "Moçambique",
    googleNames: ["Mozambique", "Republic of Mozambique"],
    currencyCode: "MZN",
    currency: "MT",
    telCode: 258,
    flag: "🇲🇿",
  },
  {
    code: "MM",
    name: "Myanmar",
    locale: "မြန်မာ",
    googleNames: ["Myanmar", "Republic of the Union of Myanmar"],
    currencyCode: "MMK",
    currency: "K",
    telCode: 95,
    flag: "🇲🇲",
  },
  {
    code: "NA",
    name: "Namibia",
    locale: "Namibia",
    googleNames: ["Namibia", "Republic of Namibia"],
    currencyCode: "NAD",
    currency: "$",
    telCode: 264,
    flag: "🇳🇦",
  },
  {
    code: "NR",
    name: "Nauru",
    locale: "Nauru",
    googleNames: ["Nauru", "Republic of Nauru"],
    currencyCode: "AUD",
    currency: "$",
    telCode: 674,
    flag: "🇳🇷",
  },
  {
    code: "NP",
    name: "Nepal",
    locale: "नेपाल",
    googleNames: ["Nepal", "Federal Democratic Republic of Nepal"],
    currencyCode: "NPR",
    currency: "₨",
    telCode: 977,
    flag: "🇳🇵",
  },
  {
    code: "NL",
    name: "Netherlands",
    locale: "Nederland",
    googleNames: ["Netherlands", "Kingdom of the Netherlands"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 31,
    flag: "🇳🇱",
  },
  {
    code: "NZ",
    name: "New Zealand",
    locale: "Aotearoa",
    googleNames: ["New Zealand"],
    currencyCode: "NZD",
    currency: "$",
    telCode: 64,
    flag: "🇳🇿",
  },
  {
    code: "NI",
    name: "Nicaragua",
    locale: "Nicaragua",
    googleNames: ["Nicaragua", "Republic of Nicaragua"],
    currencyCode: "NIO",
    currency: "C$",
    telCode: 505,
    flag: "🇳🇮",
  },
  {
    code: "NE",
    name: "Niger",
    locale: "Niger",
    googleNames: ["Niger", "Republic of Niger"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 227,
    flag: "🇳🇪",
  },
  {
    code: "NG",
    name: "Nigeria",
    locale: "Nigeria",
    googleNames: ["Nigeria", "Federal Republic of Nigeria"],
    currencyCode: "NGN",
    currency: "₦",
    telCode: 234,
    flag: "🇳🇬",
  },
  {
    code: "NU",
    name: "Niue",
    locale: "Niuē",
    googleNames: ["Niue"],
    currencyCode: "NZD",
    currency: "$",
    telCode: 683,
    flag: "🇳🇺",
  },
  {
    code: "NO",
    name: "Norway",
    locale: "Norge",
    googleNames: ["Norway", "Kingdom of Norway"],
    currencyCode: "NOK",
    currency: "kr",
    telCode: 47,
    flag: "🇳🇴",
  },
  {
    code: "OM",
    name: "Oman",
    locale: "عمان",
    googleNames: ["Oman", "Sultanate of Oman"],
    currencyCode: "OMR",
    currency: "ر.ع.",
    telCode: 968,
    flag: "🇴🇲",
  },
  {
    code: "PK",
    name: "Pakistan",
    locale: "پاکستان",
    googleNames: ["Pakistan", "Islamic Republic of Pakistan"],
    currencyCode: "PKR",
    currency: "₨",
    telCode: 92,
    flag: "🇵🇰",
  },
  {
    code: "PW",
    name: "Palau",
    locale: "Palau",
    googleNames: ["Palau", "Republic of Palau"],
    currencyCode: "USD",
    currency: "$",
    telCode: 680,
    flag: "🇵🇼",
  },
  {
    code: "PS",
    name: "Palestine",
    locale: "فلسطين",
    googleNames: ["Palestine", "State of Palestine"],
    currencyCode: "ILS",
    currency: "₪",
    telCode: 970,
    flag: "🇵🇸",
  },
  {
    code: "PA",
    name: "Panama",
    locale: "Panamá",
    googleNames: ["Panama", "Republic of Panama"],
    currencyCode: "PAB",
    currency: "B/.",
    telCode: 507,
    flag: "🇵🇦",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    locale: "Papua Niugini",
    googleNames: ["Papua New Guinea"],
    currencyCode: "PGK",
    currency: "K",
    telCode: 675,
    flag: "🇵🇬",
  },
  {
    code: "PY",
    name: "Paraguay",
    locale: "Paraguay",
    googleNames: ["Paraguay", "Republic of Paraguay"],
    currencyCode: "PYG",
    currency: "₲",
    telCode: 595,
    flag: "🇵🇾",
  },
  {
    code: "PE",
    name: "Peru",
    locale: "Perú",
    googleNames: ["Peru", "Republic of Peru"],
    currencyCode: "PEN",
    currency: "S/",
    telCode: 51,
    flag: "🇵🇪",
  },
  {
    code: "PH",
    name: "Philippines",
    locale: "Pilipinas",
    googleNames: ["Philippines", "Republic of the Philippines"],
    currencyCode: "PHP",
    currency: "₱",
    telCode: 63,
    flag: "🇵🇭",
  },
  {
    code: "PL",
    name: "Poland",
    locale: "Polska",
    googleNames: ["Poland", "Republic of Poland"],
    currencyCode: "PLN",
    currency: "zł",
    telCode: 48,
    flag: "🇵🇱",
  },
  {
    code: "PT",
    name: "Portugal",
    locale: "Portugal",
    googleNames: ["Portugal", "Portuguese Republic"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 351,
    flag: "🇵🇹",
  },
  {
    code: "QA",
    name: "Qatar",
    locale: "قطر",
    googleNames: ["Qatar", "State of Qatar"],
    currencyCode: "QAR",
    currency: "ر.ق",
    telCode: 974,
    flag: "🇶🇦",
  },
  {
    code: "RO",
    name: "Romania",
    locale: "România",
    googleNames: ["Romania"],
    currencyCode: "RON",
    currency: "lei",
    telCode: 40,
    flag: "🇷🇴",
  },
  {
    code: "RU",
    name: "Russia",
    locale: "Россия",
    googleNames: ["Russia", "Russian Federation"],
    currencyCode: "RUB",
    currency: "₽",
    telCode: 7,
    flag: "🇷🇺",
  },
  {
    code: "RW",
    name: "Rwanda",
    locale: "Rwanda",
    googleNames: ["Rwanda", "Republic of Rwanda"],
    currencyCode: "RWF",
    currency: "Fr",
    telCode: 250,
    flag: "🇷🇼",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    locale: "Saint Kitts and Nevis",
    googleNames: ["Saint Kitts and Nevis"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1869,
    flag: "🇰🇳",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    locale: "Saint Lucia",
    googleNames: ["Saint Lucia"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1758,
    flag: "🇱🇨",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    locale: "Saint Vincent and the Grenadines",
    googleNames: ["Saint Vincent and the Grenadines"],
    currencyCode: "XCD",
    currency: "$",
    telCode: 1784,
    flag: "🇻🇨",
  },
  {
    code: "WS",
    name: "Samoa",
    locale: "Samoa",
    googleNames: ["Samoa", "Independent State of Samoa"],
    currencyCode: "WST",
    currency: "T",
    telCode: 685,
    flag: "🇼🇸",
  },
  {
    code: "SM",
    name: "San Marino",
    locale: "San Marino",
    googleNames: ["San Marino", "Republic of San Marino"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 378,
    flag: "🇸🇲",
  },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    locale: "São Tomé e Príncipe",
    googleNames: ["São Tomé and Príncipe"],
    currencyCode: "STN",
    currency: "Db",
    telCode: 239,
    flag: "🇸🇹",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    locale: "السعودية",
    googleNames: ["Saudi Arabia", "Kingdom of Saudi Arabia"],
    currencyCode: "SAR",
    currency: "ر.س",
    telCode: 966,
    flag: "🇸🇦",
  },
  {
    code: "SN",
    name: "Senegal",
    locale: "Sénégal",
    googleNames: ["Senegal", "Republic of Senegal"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 221,
    flag: "🇸🇳",
  },
  {
    code: "RS",
    name: "Serbia",
    locale: "Србија",
    googleNames: ["Serbia", "Republic of Serbia"],
    currencyCode: "RSD",
    currency: "дин",
    telCode: 381,
    flag: "🇷🇸",
  },
  {
    code: "SC",
    name: "Seychelles",
    locale: "Sesel",
    googleNames: ["Seychelles", "Republic of Seychelles"],
    currencyCode: "SCR",
    currency: "₨",
    telCode: 248,
    flag: "🇸🇨",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    locale: "Sierra Leone",
    googleNames: ["Sierra Leone", "Republic of Sierra Leone"],
    currencyCode: "SLL",
    currency: "Le",
    telCode: 232,
    flag: "🇸🇱",
  },
  {
    code: "SG",
    name: "Singapore",
    locale: "Singapore",
    googleNames: ["Singapore", "Republic of Singapore"],
    currencyCode: "SGD",
    currency: "$",
    telCode: 65,
    flag: "🇸🇬",
  },
  {
    code: "SK",
    name: "Slovakia",
    locale: "Slovensko",
    googleNames: ["Slovakia", "Slovak Republic"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 421,
    flag: "🇸🇰",
  },
  {
    code: "SI",
    name: "Slovenia",
    locale: "Slovenija",
    googleNames: ["Slovenia", "Republic of Slovenia"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 386,
    flag: "🇸🇮",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    locale: "Solomon Islands",
    googleNames: ["Solomon Islands"],
    currencyCode: "SBD",
    currency: "$",
    telCode: 677,
    flag: "🇸🇧",
  },
  {
    code: "SO",
    name: "Somalia",
    locale: "Soomaaliya",
    googleNames: ["Somalia", "Federal Republic of Somalia"],
    currencyCode: "SOS",
    currency: "Sh",
    telCode: 252,
    flag: "🇸🇴",
  },
  {
    code: "ZA",
    name: "South Africa",
    locale: "South Africa",
    googleNames: ["South Africa", "Republic of South Africa"],
    currencyCode: "ZAR",
    currency: "R",
    telCode: 27,
    flag: "🇿🇦",
  },
  {
    code: "SS",
    name: "South Sudan",
    locale: "South Sudan",
    googleNames: ["South Sudan", "Republic of South Sudan"],
    currencyCode: "SSP",
    currency: "£",
    telCode: 211,
    flag: "🇸🇸",
  },
  {
    code: "ES",
    name: "Spain",
    locale: "España",
    googleNames: ["Spain", "Kingdom of Spain"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 34,
    flag: "🇪🇸",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    locale: "ශ්‍රී ලංකා",
    googleNames: ["Sri Lanka", "Democratic Socialist Republic of Sri Lanka"],
    currencyCode: "LKR",
    currency: "₨",
    telCode: 94,
    flag: "🇱🇰",
  },
  {
    code: "SD",
    name: "Sudan",
    locale: "السودان",
    googleNames: ["Sudan", "Republic of the Sudan"],
    currencyCode: "SDG",
    currency: "£",
    telCode: 249,
    flag: "🇸🇩",
  },
  {
    code: "SR",
    name: "Suriname",
    locale: "Suriname",
    googleNames: ["Suriname", "Republic of Suriname"],
    currencyCode: "SRD",
    currency: "$",
    telCode: 597,
    flag: "🇸🇷",
  },
  {
    code: "SE",
    name: "Sweden",
    locale: "Sverige",
    googleNames: ["Sweden", "Kingdom of Sweden"],
    currencyCode: "SEK",
    currency: "kr",
    telCode: 46,
    flag: "🇸🇪",
  },
  {
    code: "CH",
    name: "Switzerland",
    locale: "Schweiz",
    googleNames: ["Switzerland", "Swiss Confederation"],
    currencyCode: "CHF",
    currency: "Fr",
    telCode: 41,
    flag: "🇨🇭",
  },
  {
    code: "SY",
    name: "Syria",
    locale: "سوريا",
    googleNames: ["Syria", "Syrian Arab Republic"],
    currencyCode: "SYP",
    currency: "£",
    telCode: 963,
    flag: "🇸🇾",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    locale: "Тоҷикистон",
    googleNames: ["Tajikistan", "Republic of Tajikistan"],
    currencyCode: "TJS",
    currency: "SM",
    telCode: 992,
    flag: "🇹🇯",
  },
  {
    code: "TZ",
    name: "Tanzania",
    locale: "Tanzania",
    googleNames: ["Tanzania", "United Republic of Tanzania"],
    currencyCode: "TZS",
    currency: "Sh",
    telCode: 255,
    flag: "🇹🇿",
  },
  {
    code: "TH",
    name: "Thailand",
    locale: "ประเทศไทย",
    googleNames: ["Thailand", "Kingdom of Thailand"],
    currencyCode: "THB",
    currency: "฿",
    telCode: 66,
    flag: "🇹🇭",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    locale: "Timor-Leste",
    googleNames: ["Timor-Leste", "East Timor"],
    currencyCode: "USD",
    currency: "$",
    telCode: 670,
    flag: "🇹🇱",
  },
  {
    code: "TG",
    name: "Togo",
    locale: "Togo",
    googleNames: ["Togo", "Togolese Republic"],
    currencyCode: "XOF",
    currency: "CFA",
    telCode: 228,
    flag: "🇹🇬",
  },
  {
    code: "TO",
    name: "Tonga",
    locale: "Tonga",
    googleNames: ["Tonga", "Kingdom of Tonga"],
    currencyCode: "TOP",
    currency: "T$",
    telCode: 676,
    flag: "🇹🇴",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    locale: "Trinidad and Tobago",
    googleNames: ["Trinidad and Tobago", "Republic of Trinidad and Tobago"],
    currencyCode: "TTD",
    currency: "$",
    telCode: 1868,
    flag: "🇹🇹",
  },
  {
    code: "TN",
    name: "Tunisia",
    locale: "تونس",
    googleNames: ["Tunisia", "Republic of Tunisia"],
    currencyCode: "TND",
    currency: "د.ت",
    telCode: 216,
    flag: "🇹🇳",
  },
  {
    code: "TR",
    name: "Turkey",
    locale: "Türkiye",
    googleNames: ["Turkey", "Republic of Turkey"],
    currencyCode: "TRY",
    currency: "₺",
    telCode: 90,
    flag: "🇹🇷",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    locale: "Türkmenistan",
    googleNames: ["Turkmenistan"],
    currencyCode: "TMT",
    currency: "m",
    telCode: 993,
    flag: "🇹🇲",
  },
  {
    code: "TV",
    name: "Tuvalu",
    locale: "Tuvalu",
    googleNames: ["Tuvalu"],
    currencyCode: "AUD",
    currency: "$",
    telCode: 688,
    flag: "🇹🇻",
  },
  {
    code: "UG",
    name: "Uganda",
    locale: "Uganda",
    googleNames: ["Uganda", "Republic of Uganda"],
    currencyCode: "UGX",
    currency: "Sh",
    telCode: 256,
    flag: "🇺🇬",
  },
  {
    code: "UA",
    name: "Ukraine",
    locale: "Україна",
    googleNames: ["Ukraine"],
    currencyCode: "UAH",
    currency: "₴",
    telCode: 380,
    flag: "🇺🇦",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    locale: "الإمارات العربية المتحدة",
    googleNames: ["United Arab Emirates", "UAE"],
    currencyCode: "AED",
    currency: "د.إ",
    telCode: 971,
    flag: "🇦🇪",
  },
  {
    code: "GB",
    name: "United Kingdom",
    locale: "United Kingdom",
    googleNames: ["United Kingdom", "UK", "Great Britain"],
    currencyCode: "GBP",
    currency: "£",
    telCode: 44,
    flag: "🇬🇧",
  },
  {
    code: "US",
    name: "United States",
    locale: "United States",
    googleNames: ["United States", "USA", "United States of America"],
    currencyCode: "USD",
    currency: "$",
    telCode: 1,
    flag: "🇺🇸",
  },
  {
    code: "UY",
    name: "Uruguay",
    locale: "Uruguay",
    googleNames: ["Uruguay", "Oriental Republic of Uruguay"],
    currencyCode: "UYU",
    currency: "$",
    telCode: 598,
    flag: "🇺🇾",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    locale: "Oʻzbekiston",
    googleNames: ["Uzbekistan", "Republic of Uzbekistan"],
    currencyCode: "UZS",
    currency: "сўм",
    telCode: 998,
    flag: "🇺🇿",
  },
  {
    code: "VU",
    name: "Vanuatu",
    locale: "Vanuatu",
    googleNames: ["Vanuatu", "Republic of Vanuatu"],
    currencyCode: "VUV",
    currency: "Vt",
    telCode: 678,
    flag: "🇻🇺",
  },
  {
    code: "VA",
    name: "Vatican City",
    locale: "Città del Vaticano",
    googleNames: ["Vatican City", "Holy See"],
    currencyCode: "EUR",
    currency: "€",
    telCode: 379,
    flag: "🇻🇦",
  },
  {
    code: "VE",
    name: "Venezuela",
    locale: "Venezuela",
    googleNames: ["Venezuela", "Bolivarian Republic of Venezuela"],
    currencyCode: "VES",
    currency: "Bs.",
    telCode: 58,
    flag: "🇻🇪",
  },
  {
    code: "VN",
    name: "Vietnam",
    locale: "Việt Nam",
    googleNames: ["Vietnam", "Socialist Republic of Vietnam"],
    currencyCode: "VND",
    currency: "₫",
    telCode: 84,
    flag: "🇻🇳",
  },
  {
    code: "YE",
    name: "Yemen",
    locale: "اليمن",
    googleNames: ["Yemen", "Republic of Yemen"],
    currencyCode: "YER",
    currency: "﷼",
    telCode: 967,
    flag: "🇾🇪",
  },
  {
    code: "ZM",
    name: "Zambia",
    locale: "Zambia",
    googleNames: ["Zambia", "Republic of Zambia"],
    currencyCode: "ZMW",
    currency: "ZK",
    telCode: 260,
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    locale: "Zimbabwe",
    googleNames: ["Zimbabwe", "Republic of Zimbabwe"],
    currencyCode: "ZWL",
    currency: "$",
    telCode: 263,
    flag: "🇿🇼",
  },
];