import { LanguageType } from "./const-type";

export const languages: LanguageType[] = [
  {
    lang: "ps-AF",
    code: "ps",
    country: "AF",
    name: "Pashto",
    dir: "rtl",
    locale: "پښتو",
  },
  {
    lang: "sq-AL",
    code: "sq",
    country: "AL",
    name: "Albanian",
    dir: "ltr",
    locale: "Shqip",
  },
  {
    lang: "ar-DZ",
    code: "ar",
    country: "DZ",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "ca-AD",
    code: "ca",
    country: "AD",
    name: "Catalan",
    dir: "ltr",
    locale: "Català",
  },
  {
    lang: "pt-AO",
    code: "pt",
    country: "AO",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "en-AG",
    code: "en",
    country: "AG",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-AR",
    code: "es",
    country: "AR",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "hy-AM",
    code: "hy",
    country: "AM",
    name: "Armenian",
    dir: "ltr",
    locale: "Հայերեն",
  },
  {
    lang: "en-AU",
    code: "en",
    country: "AU",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "de-AT",
    code: "de",
    country: "AT",
    name: "German",
    dir: "ltr",
    locale: "Deutsch",
  },
  {
    lang: "az-AZ",
    code: "az",
    country: "AZ",
    name: "Azerbaijani",
    dir: "ltr",
    locale: "Azərbaycan",
  },
  {
    lang: "en-BS",
    code: "en",
    country: "BS",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ar-BH",
    code: "ar",
    country: "BH",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "bn-BD",
    code: "bn",
    country: "BD",
    name: "Bengali",
    dir: "ltr",
    locale: "বাংলা",
  },
  {
    lang: "en-BB",
    code: "en",
    country: "BB",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "be-BY",
    code: "be",
    country: "BY",
    name: "Belarusian",
    dir: "ltr",
    locale: "Беларуская",
  },
  {
    lang: "nl-BE",
    code: "nl",
    country: "BE",
    name: "Dutch",
    dir: "ltr",
    locale: "Nederlands",
  },
  {
    lang: "en-BZ",
    code: "en",
    country: "BZ",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "fr-BJ",
    code: "fr",
    country: "BJ",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "dz-BT",
    code: "dz",
    country: "BT",
    name: "Dzongkha",
    dir: "ltr",
    locale: "ཇོང་ཁ",
  },
  {
    lang: "es-BO",
    code: "es",
    country: "BO",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "bs-BA",
    code: "bs",
    country: "BA",
    name: "Bosnian",
    dir: "ltr",
    locale: "Bosanski",
  },
  {
    lang: "en-BW",
    code: "en",
    country: "BW",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "pt-BR",
    code: "pt",
    country: "BR",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "ms-BN",
    code: "ms",
    country: "BN",
    name: "Malay",
    dir: "ltr",
    locale: "Bahasa Melayu",
  },
  {
    lang: "bg-BG",
    code: "bg",
    country: "BG",
    name: "Bulgarian",
    dir: "ltr",
    locale: "Български",
  },
  {
    lang: "fr-BF",
    code: "fr",
    country: "BF",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "rn-BI",
    code: "rn",
    country: "BI",
    name: "Kirundi",
    dir: "ltr",
    locale: "Ikirundi",
  },
  {
    lang: "pt-CV",
    code: "pt",
    country: "CV",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "km-KH",
    code: "km",
    country: "KH",
    name: "Khmer",
    dir: "ltr",
    locale: "ខ្មែរ",
  },
  {
    lang: "fr-CM",
    code: "fr",
    country: "CM",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "en-CA",
    code: "en",
    country: "CA",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "fr-CF",
    code: "fr",
    country: "CF",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "fr-TD",
    code: "fr",
    country: "TD",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "es-CL",
    code: "es",
    country: "CL",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "zh-CN",
    code: "zh",
    country: "CN",
    name: "Chinese (Simplified)",
    dir: "ltr",
    locale: "中文 (简体)",
  },
  {
    lang: "es-CO",
    code: "es",
    country: "CO",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "ar-KM",
    code: "ar",
    country: "KM",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "fr-CG",
    code: "fr",
    country: "CG",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "fr-CD",
    code: "fr",
    country: "CD",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "es-CR",
    code: "es",
    country: "CR",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "fr-CI",
    code: "fr",
    country: "CI",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "hr-HR",
    code: "hr",
    country: "HR",
    name: "Croatian",
    dir: "ltr",
    locale: "Hrvatski",
  },
  {
    lang: "es-CU",
    code: "es",
    country: "CU",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "el-CY",
    code: "el",
    country: "CY",
    name: "Greek",
    dir: "ltr",
    locale: "Ελληνικά",
  },
  {
    lang: "cs-CZ",
    code: "cs",
    country: "CZ",
    name: "Czech",
    dir: "ltr",
    locale: "Čeština",
  },
  {
    lang: "da-DK",
    code: "da",
    country: "DK",
    name: "Danish",
    dir: "ltr",
    locale: "Dansk",
  },
  {
    lang: "fr-DJ",
    code: "fr",
    country: "DJ",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "en-DM",
    code: "en",
    country: "DM",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-DO",
    code: "es",
    country: "DO",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "es-EC",
    code: "es",
    country: "EC",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "ar-EG",
    code: "ar",
    country: "EG",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "es-SV",
    code: "es",
    country: "SV",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "es-GQ",
    code: "es",
    country: "GQ",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "ti-ER",
    code: "ti",
    country: "ER",
    name: "Tigrinya",
    dir: "ltr",
    locale: "ትግርኛ",
  },
  {
    lang: "et-EE",
    code: "et",
    country: "EE",
    name: "Estonian",
    dir: "ltr",
    locale: "Eesti",
  },
  {
    lang: "si-SZ",
    code: "si",
    country: "SZ",
    name: "Swati",
    dir: "ltr",
    locale: "SiSwati",
  },
  {
    lang: "am-ET",
    code: "am",
    country: "ET",
    name: "Amharic",
    dir: "ltr",
    locale: "አማርኛ",
  },
  {
    lang: "en-FJ",
    code: "en",
    country: "FJ",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "fi-FI",
    code: "fi",
    country: "FI",
    name: "Finnish",
    dir: "ltr",
    locale: "Suomi",
  },
  {
    lang: "fr-FR",
    code: "fr",
    country: "FR",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "fr-GA",
    code: "fr",
    country: "GA",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "en-GM",
    code: "en",
    country: "GM",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ka-GE",
    code: "ka",
    country: "GE",
    name: "Georgian",
    dir: "ltr",
    locale: "ქართული",
  },
  {
    lang: "de-DE",
    code: "de",
    country: "DE",
    name: "German",
    dir: "ltr",
    locale: "Deutsch",
  },
  {
    lang: "en-GH",
    code: "en",
    country: "GH",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "el-GR",
    code: "el",
    country: "GR",
    name: "Greek",
    dir: "ltr",
    locale: "Ελληνικά",
  },
  {
    lang: "en-GD",
    code: "en",
    country: "GD",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-GT",
    code: "es",
    country: "GT",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "fr-GN",
    code: "fr",
    country: "GN",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "pt-GW",
    code: "pt",
    country: "GW",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "en-GY",
    code: "en",
    country: "GY",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "fr-HT",
    code: "fr",
    country: "HT",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "es-HN",
    code: "es",
    country: "HN",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "hu-HU",
    code: "hu",
    country: "HU",
    name: "Hungarian",
    dir: "ltr",
    locale: "Magyar",
  },
  {
    lang: "is-IS",
    code: "is",
    country: "IS",
    name: "Icelandic",
    dir: "ltr",
    locale: "Íslenska",
  },
  {
    lang: "hi-IN",
    code: "hi",
    country: "IN",
    name: "Hindi",
    dir: "ltr",
    locale: "हिन्दी",
  },
  {
    lang: "kn-IN",
    code: "kn",
    country: "IN",
    name: "Kannada",
    dir: "ltr",
    locale: "ಕನ್ನಡ",
  },
  {
    lang: "ta-IN",
    code: "ta",
    country: "IN",
    name: "Tamil",
    dir: "ltr",
    locale: "தமிழ்",
  },
  {
    lang: "te-IN",
    code: "te",
    country: "IN",
    name: "Telugu",
    dir: "ltr",
    locale: "తెలుగు",
  },
  {
    lang: "bn-IN",
    code: "bn",
    country: "IN",
    name: "Bengali",
    dir: "ltr",
    locale: "বাংলা",
  },
  {
    lang: "mr-IN",
    code: "mr",
    country: "IN",
    name: "Marathi",
    dir: "ltr",
    locale: "मराठी",
  },
  {
    lang: "gu-IN",
    code: "gu",
    country: "IN",
    name: "Gujarati",
    dir: "ltr",
    locale: "ગુજરાતી",
  },
  {
    lang: "ml-IN",
    code: "ml",
    country: "IN",
    name: "Malayalam",
    dir: "ltr",
    locale: "മലയാളം",
  },
  {
    lang: "pa-IN",
    code: "pa",
    country: "IN",
    name: "Punjabi",
    dir: "ltr",
    locale: "ਪੰਜਾਬੀ",
  },
  {
    lang: "or-IN",
    code: "or",
    country: "IN",
    name: "Odia",
    dir: "ltr",
    locale: "ଓଡ଼ିଆ",
  },
  {
    lang: "as-IN",
    code: "as",
    country: "IN",
    name: "Assamese",
    dir: "ltr",
    locale: "অসমীয়া",
  },
  {
    lang: "id-ID",
    code: "id",
    country: "ID",
    name: "Indonesian",
    dir: "ltr",
    locale: "Bahasa Indonesia",
  },
  {
    lang: "fa-IR",
    code: "fa",
    country: "IR",
    name: "Persian",
    dir: "rtl",
    locale: "فارسی",
  },
  {
    lang: "ar-IQ",
    code: "ar",
    country: "IQ",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "ga-IE",
    code: "ga",
    country: "IE",
    name: "Irish",
    dir: "ltr",
    locale: "Gaelige",
  },
  {
    lang: "he-IL",
    code: "he",
    country: "IL",
    name: "Hebrew",
    dir: "rtl",
    locale: "עברית",
  },
  {
    lang: "it-IT",
    code: "it",
    country: "IT",
    name: "Italian",
    dir: "ltr",
    locale: "Italiano",
  },
  {
    lang: "en-JM",
    code: "en",
    country: "JM",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ja-JP",
    code: "ja",
    country: "JP",
    name: "Japanese",
    dir: "ltr",
    locale: "日本語",
  },
  {
    lang: "ar-JO",
    code: "ar",
    country: "JO",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "kk-KZ",
    code: "kk",
    country: "KZ",
    name: "Kazakh",
    dir: "ltr",
    locale: "Қазақша",
  },
  {
    lang: "sw-KE",
    code: "sw",
    country: "KE",
    name: "Swahili",
    dir: "ltr",
    locale: "Kiswahili",
  },
  {
    lang: "en-KI",
    code: "en",
    country: "KI",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ko-KP",
    code: "ko",
    country: "KP",
    name: "Korean",
    dir: "ltr",
    locale: "한국어",
  },
  {
    lang: "ko-KR",
    code: "ko",
    country: "KR",
    name: "Korean",
    dir: "ltr",
    locale: "한국어",
  },
  {
    lang: "ar-KW",
    code: "ar",
    country: "KW",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "ky-KG",
    code: "ky",
    country: "KG",
    name: "Kyrgyz",
    dir: "ltr",
    locale: "Кыргызча",
  },
  {
    lang: "lo-LA",
    code: "lo",
    country: "LA",
    name: "Lao",
    dir: "ltr",
    locale: "ລາວ",
  },
  {
    lang: "lv-LV",
    code: "lv",
    country: "LV",
    name: "Latvian",
    dir: "ltr",
    locale: "Latviešu",
  },
  {
    lang: "ar-LB",
    code: "ar",
    country: "LB",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "st-LS",
    code: "st",
    country: "LS",
    name: "Sesotho",
    dir: "ltr",
    locale: "Sesotho",
  },
  {
    lang: "en-LR",
    code: "en",
    country: "LR",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ar-LY",
    code: "ar",
    country: "LY",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "de-LI",
    code: "de",
    country: "LI",
    name: "German",
    dir: "ltr",
    locale: "Deutsch",
  },
  {
    lang: "lt-LT",
    code: "lt",
    country: "LT",
    name: "Lithuanian",
    dir: "ltr",
    locale: "Lietuvių",
  },
  {
    lang: "fr-LU",
    code: "fr",
    country: "LU",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "mg-MG",
    code: "mg",
    country: "MG",
    name: "Malagasy",
    dir: "ltr",
    locale: "Malagasy",
  },
  {
    lang: "ny-MW",
    code: "ny",
    country: "MW",
    name: "Chichewa",
    dir: "ltr",
    locale: "Chichewa",
  },
  {
    lang: "ms-MY",
    code: "ms",
    country: "MY",
    name: "Malay",
    dir: "ltr",
    locale: "Bahasa Melayu",
  },
  {
    lang: "dv-MV",
    code: "dv",
    country: "MV",
    name: "Dhivehi",
    dir: "rtl",
    locale: "ދިވެހި",
  },
  {
    lang: "fr-ML",
    code: "fr",
    country: "ML",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "mt-MT",
    code: "mt",
    country: "MT",
    name: "Maltese",
    dir: "ltr",
    locale: "Malti",
  },
  {
    lang: "en-MH",
    code: "en",
    country: "MH",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ar-MR",
    code: "ar",
    country: "MR",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "en-MU",
    code: "en",
    country: "MU",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-MX",
    code: "es",
    country: "MX",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "en-FM",
    code: "en",
    country: "FM",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ro-MD",
    code: "ro",
    country: "MD",
    name: "Romanian",
    dir: "ltr",
    locale: "Română",
  },
  {
    lang: "fr-MC",
    code: "fr",
    country: "MC",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "mn-MN",
    code: "mn",
    country: "MN",
    name: "Mongolian",
    dir: "ltr",
    locale: "Монгол",
  },
  {
    lang: "sr-ME",
    code: "sr",
    country: "ME",
    name: "Serbian",
    dir: "ltr",
    locale: "Српски",
  },
  {
    lang: "ar-MA",
    code: "ar",
    country: "MA",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "pt-MZ",
    code: "pt",
    country: "MZ",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "my-MM",
    code: "my",
    country: "MM",
    name: "Burmese",
    dir: "ltr",
    locale: "မြန်မာ",
  },
  {
    lang: "en-NA",
    code: "en",
    country: "NA",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-NR",
    code: "en",
    country: "NR",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ne-NP",
    code: "ne",
    country: "NP",
    name: "Nepali",
    dir: "ltr",
    locale: "नेपाली",
  },
  {
    lang: "nl-NL",
    code: "nl",
    country: "NL",
    name: "Dutch",
    dir: "ltr",
    locale: "Nederlands",
  },
  {
    lang: "en-NZ",
    code: "en",
    country: "NZ",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-NI",
    code: "es",
    country: "NI",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "fr-NE",
    code: "fr",
    country: "NE",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "en-NG",
    code: "en",
    country: "NG",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "yo-NG",
    code: "yo",
    country: "NG",
    name: "Yoruba",
    dir: "ltr",
    locale: "Yorùbá",
  },
  {
    lang: "ha-NG",
    code: "ha",
    country: "NG",
    name: "Hausa",
    dir: "ltr",
    locale: "Hausa",
  },
  {
    lang: "ig-NG",
    code: "ig",
    country: "NG",
    name: "Igbo",
    dir: "ltr",
    locale: "Igbo",
  },
  {
    lang: "en-NU",
    code: "en",
    country: "NU",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "nb-NO",
    code: "nb",
    country: "NO",
    name: "Norwegian Bokmål",
    dir: "ltr",
    locale: "Norsk Bokmål",
  },
  {
    lang: "ar-OM",
    code: "ar",
    country: "OM",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "ur-PK",
    code: "ur",
    country: "PK",
    name: "Urdu",
    dir: "rtl",
    locale: "اردو",
  },
  {
    lang: "en-PW",
    code: "en",
    country: "PW",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ar-PS",
    code: "ar",
    country: "PS",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "es-PA",
    code: "es",
    country: "PA",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "en-PG",
    code: "en",
    country: "PG",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-PY",
    code: "es",
    country: "PY",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "es-PE",
    code: "es",
    country: "PE",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "tl-PH",
    code: "tl",
    country: "PH",
    name: "Tagalog",
    dir: "ltr",
    locale: "Tagalog",
  },
  {
    lang: "pl-PL",
    code: "pl",
    country: "PL",
    name: "Polish",
    dir: "ltr",
    locale: "Polski",
  },
  {
    lang: "pt-PT",
    code: "pt",
    country: "PT",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "ar-QA",
    code: "ar",
    country: "QA",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "ro-RO",
    code: "ro",
    country: "RO",
    name: "Romanian",
    dir: "ltr",
    locale: "Română",
  },
  {
    lang: "ru-RU",
    code: "ru",
    country: "RU",
    name: "Russian",
    dir: "ltr",
    locale: "Русский",
  },
  {
    lang: "rw-RW",
    code: "rw",
    country: "RW",
    name: "Kinyarwanda",
    dir: "ltr",
    locale: "Ikinyarwanda",
  },
  {
    lang: "en-KN",
    code: "en",
    country: "KN",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-LC",
    code: "en",
    country: "LC",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-VC",
    code: "en",
    country: "VC",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "sm-WS",
    code: "sm",
    country: "WS",
    name: "Samoan",
    dir: "ltr",
    locale: "Gagana Samoa",
  },
  {
    lang: "it-SM",
    code: "it",
    country: "SM",
    name: "Italian",
    dir: "ltr",
    locale: "Italiano",
  },
  {
    lang: "pt-ST",
    code: "pt",
    country: "ST",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "ar-SA",
    code: "ar",
    country: "SA",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "fr-SN",
    code: "fr",
    country: "SN",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "sr-RS",
    code: "sr",
    country: "RS",
    name: "Serbian",
    dir: "ltr",
    locale: "Српски",
  },
  {
    lang: "en-SC",
    code: "en",
    country: "SC",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-SL",
    code: "en",
    country: "SL",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-SG",
    code: "en",
    country: "SG",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "sk-SK",
    code: "sk",
    country: "SK",
    name: "Slovak",
    dir: "ltr",
    locale: "Slovenčina",
  },
  {
    lang: "sl-SI",
    code: "sl",
    country: "SI",
    name: "Slovenian",
    dir: "ltr",
    locale: "Slovenščina",
  },
  {
    lang: "en-SB",
    code: "en",
    country: "SB",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "so-SO",
    code: "so",
    country: "SO",
    name: "Somali",
    dir: "ltr",
    locale: "Soomaali",
  },
  {
    lang: "af-ZA",
    code: "af",
    country: "ZA",
    name: "Afrikaans",
    dir: "ltr",
    locale: "Afrikaans",
  },
  {
    lang: "en-SS",
    code: "en",
    country: "SS",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-ES",
    code: "es",
    country: "ES",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "si-LK",
    code: "si",
    country: "LK",
    name: "Sinhala",
    dir: "ltr",
    locale: "සිංහල",
  },
  {
    lang: "ar-SD",
    code: "ar",
    country: "SD",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "nl-SR",
    code: "nl",
    country: "SR",
    name: "Dutch",
    dir: "ltr",
    locale: "Nederlands",
  },
  {
    lang: "sv-SE",
    code: "sv",
    country: "SE",
    name: "Swedish",
    dir: "ltr",
    locale: "Svenska",
  },
  {
    lang: "de-CH",
    code: "de",
    country: "CH",
    name: "German",
    dir: "ltr",
    locale: "Deutsch",
  },
  {
    lang: "ar-SY",
    code: "ar",
    country: "SY",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "tg-TJ",
    code: "tg",
    country: "TJ",
    name: "Tajik",
    dir: "ltr",
    locale: "Тоҷикӣ",
  },
  {
    lang: "sw-TZ",
    code: "sw",
    country: "TZ",
    name: "Swahili",
    dir: "ltr",
    locale: "Kiswahili",
  },
  {
    lang: "th-TH",
    code: "th",
    country: "TH",
    name: "Thai",
    dir: "ltr",
    locale: "ไทย",
  },
  {
    lang: "pt-TL",
    code: "pt",
    country: "TL",
    name: "Portuguese",
    dir: "ltr",
    locale: "Português",
  },
  {
    lang: "fr-TG",
    code: "fr",
    country: "TG",
    name: "French",
    dir: "ltr",
    locale: "Français",
  },
  {
    lang: "to-TO",
    code: "to",
    country: "TO",
    name: "Tongan",
    dir: "ltr",
    locale: "Lea Faka-Tonga",
  },
  {
    lang: "en-TT",
    code: "en",
    country: "TT",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "ar-TN",
    code: "ar",
    country: "TN",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "tr-TR",
    code: "tr",
    country: "TR",
    name: "Turkish",
    dir: "ltr",
    locale: "Türkçe",
  },
  {
    lang: "tk-TM",
    code: "tk",
    country: "TM",
    name: "Turkmen",
    dir: "ltr",
    locale: "Türkmen",
  },
  {
    lang: "en-TV",
    code: "en",
    country: "TV",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-UG",
    code: "en",
    country: "UG",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "uk-UA",
    code: "uk",
    country: "UA",
    name: "Ukrainian",
    dir: "ltr",
    locale: "Українська",
  },
  {
    lang: "ar-AE",
    code: "ar",
    country: "AE",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "en-GB",
    code: "en",
    country: "GB",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-US",
    code: "en",
    country: "US",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "es-UY",
    code: "es",
    country: "UY",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "uz-UZ",
    code: "uz",
    country: "UZ",
    name: "Uzbek",
    dir: "ltr",
    locale: "Oʻzbek",
  },
  {
    lang: "bi-VU",
    code: "bi",
    country: "VU",
    name: "Bislama",
    dir: "ltr",
    locale: "Bislama",
  },
  {
    lang: "it-VA",
    code: "it",
    country: "VA",
    name: "Italian",
    dir: "ltr",
    locale: "Italiano",
  },
  {
    lang: "es-VE",
    code: "es",
    country: "VE",
    name: "Spanish",
    dir: "ltr",
    locale: "Español",
  },
  {
    lang: "vi-VN",
    code: "vi",
    country: "VN",
    name: "Vietnamese",
    dir: "ltr",
    locale: "Tiếng Việt",
  },
  {
    lang: "ar-YE",
    code: "ar",
    country: "YE",
    name: "Arabic",
    dir: "rtl",
    locale: "العربية",
  },
  {
    lang: "en-ZM",
    code: "en",
    country: "ZM",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
  {
    lang: "en-ZW",
    code: "en",
    country: "ZW",
    name: "English",
    dir: "ltr",
    locale: "English",
  },
];

